### ISSUE TITLE
[FEATURE REQUEST] Validation for name and email in model user.js

### ISSUE THREAD

**Issue by davidalenoghena** [microapidev/comment-microapi#37] opened 2020-06-26 12:18 UTC
### Is your feature request related to a problem? Please describe.
There is no validation of the email to be entered

### Describe the solution you'd like
Validation of emails entered and to return an error when an incorrect email is sent

**Comment by The-indigo** [comment] 2020-06-27 13:32
i want to work on this

**Comment by davidalenoghena** [comment] 2020-06-28 07:30
I also want to work on it

**Comment by davidalenoghena** [comment] 2020-06-28 08:17
Can it be assigned to me?

**Comment by oscar-ekeyekwu** [comment] 2020-06-28 10:08
This issue is a duplicate of #13

**Closed by oscar-ekeyekwu** 2020-06-28 10:08 UTC
Labels: enhancement
