### ISSUE TITLE
[FEATURE REQUEST] : Create controller method to upvote a reply

### ISSUE THREAD

**Issue by Ochuwa-sophie** [microapidev/comment-microapi#159] opened 2020-06-30 14:29 UTC
The purpose of this feature is to give users the ability to upvote replies.

"RepliesController - PATCH /comments/{commentId}/replies/{replyId}/votes/upvote:
Create controller method to upvote a reply"

**Comment by davidalenoghena** [comment] 2020-06-30 20:11
Isn't this a duplicate of case #117 that is already assigned to someone?

**Comment by Ochuwa-sophie** [comment] 2020-07-01 13:40
No, this is to **upvote** a reply while #117 is to **update** a reply

**Comment by Joeedwin073** [comment] 2020-07-02 15:01
I'll like to take this task.
Thanks

**Closed** 2020-07-03 12:59 UTC
Labels: enhancement
